### ISSUE TITLE
Malt render preview turns viewport solid black with fresh build of Blender 2.91 on Linux

### ISSUE THREAD

**Issue by bxbrenden** [bnpr/Malt#24] opened 2020-12-10 00:54 UTC
### Problem Description

Using Blender NPR's [Getting Started with BEER tutorial on YouTube](https://www.youtube.com/watch?v=tnXnmcC49iU), I followed the instructions to install and configure Malt / BEER. However, on the step where the viewport shading is switched to `Rendered` (i.e. the render preview), everything in the whole 3d viewport goes black. It stays black even once I switch back to `Solid` shading. I have to exit the program fully to get the viewport back to normal.

I've included a screenshot, the steps to reproduce the issue, the Python traceback, and my personal system settings. Let me know if you need more info, and I'd be glad to help.

### Screenshot
![malt-black-screen](https://user-images.githubusercontent.com/26355516/101706967-18e5dc00-3a3f-11eb-84d4-32685bfd91c0.png)

### Steps to Reproduce the Issue

1. From the releases page, download the latest release of Malt for Linux called [BlenderMalt-Linux.zip](https://github.com/BlenderNPR/BEER/releases/download/v1-beta/BlenderMalt-Linux.zip).
2. Download the example shaders zip file called [Shader-Examples.zip](https://github.com/BlenderNPR/BEER/releases/download/v1-beta/Shader-Examples.zip).
3. Download the newest release of Blender (2.91.0) from the [official download link](https://www.blender.org/download/Blender2.91/blender-2.91.0-linux64.tar.xz/).
4. In the command line terminal, decompress the `blender-2.91.0-linux64.tar.xz` and `Shader-Examples.zip` files from steps 2-3 in a directory of your choice.
5. Change directories to the newly created `blender-2.91.0-linux64` directory, and then go to its child folder called `2.91`.
```bash
cd blender-2.91.0-linux64/2.91
```
6. Create an empty directory in there called `config`.
```bash
mkdir config
```
7. Go back to the main decompressed Blender 2.91 directory where the `blender` executable lives.
```bash
cd ..
```
8. Start blender from the command line:
```bash
./blender &
```
9. In blender, go to `Edit` -> `Preferences` -> `Add-ons`.
10. Click the `Install...` button, locate the `BlenderMalt-Linux.zip` file, and double-click it to load it.
11. In the `Add-ons` menu, check the box that enables the Malt add-on, and close the `Preferences` window.
12. In the `Render Properties` tab, change the rendering engine to `Malt`.
13. Change the default lamp to a `Sun` lamp.
14. Replace the default cube with an Ico Sphere, enable a subsurf modifier on it (level 2), and shade smooth.
15. From the `Material Properties` tab, add a new material to the Ico Sphere.
16. In the `Shader Source` selector inside the material, click the folder icon 📁.
17. Choose the `basic.mesh.glsl` shader from the list by clicking it and then clicking `Accept` (or double-clicking the shader file).
18. In the `Viewport Shading` menu at the top-right, change the shading to `Rendered` to enable the render preview.
19. The 3d viewport will turn black.

###  Python Traceback
As soon as I change the viewport shading to `Rendered`, there is an Python stack trace / traceback in the terminal.
The complete traceback message is:
```
Python: Traceback (most recent call last):
  File "/home/brenden/Software/blender-2.91.0-linux64/2.91/scripts/addons/BlenderMalt/MaltRenderEngine.py", line 282, in view_draw
    render_texture = self.get_pipeline().render(resolution, scene, False, self.request_new_frame)['COLOR']
  File "/home/brenden/Software/blender-2.91.0-linux64/2.91/scripts/addons/BlenderMalt/MaltPath/Malt/Pipeline.py", line 284, in render
    self.result = self.do_render(resolution, scene, is_final_render, is_new_frame)
  File "/home/brenden/Software/blender-2.91.0-linux64/2.91/scripts/addons/BlenderMalt/MaltPath/Malt/Pipelines/NPR_Pipeline/NPR_Pipeline.py", line 202, in do_render
    result = self.draw_layer(opaque_batches, scene, scene.world_parameters['Background Color'])
  File "/home/brenden/Software/blender-2.91.0-linux64/2.91/scripts/addons/BlenderMalt/MaltPath/Malt/Pipelines/NPR_Pipeline/NPR_Pipeline.py", line 270, in draw_layer
    self.fbo_main.clear([background_color, (0,0,0,1), (-1,-1,-1,-1)])
  File "/home/brenden/Software/blender-2.91.0-linux64/2.91/scripts/addons/BlenderMalt/MaltPath/Malt/RenderTarget.py", line 92, in clear
    glClear(flags)
  File "src/errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
OpenGL.error.GLError: GLError(
	err = 1286,
	description = b'invalid framebuffer operation',
	baseOperation = glClear,
	cArguments = (0,)
)
```

### System Settings
**Operating System**: Debian GNU/Linux 10 (buster)
**Architecture**: x86_64
**RAM**: 16GB
**Processor**: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
**Video Card**: None (embedded graphics only)

**Comment by pragma37** [comment] 2020-12-10 14:54
Hi, thanks for the detailed info report!

Seems like the OpenGL context becomes invalid at some point. Is that the first Python traceback you get ?

Does F12 rendering works? Could you try with a completely empty scene to see if that works ?

Just to discard that the issue is caused by Blender itself, could you try the [Simple Render Engine example from the Blender docs](https://docs.blender.org/api/current/bpy.types.RenderEngine.html#simple-render-engine)?

1. Open Blender and go to the scripting workspace.
2. Copy-paste the Simple Render Engine code into the text editor and click the *Run Script* (play icon) button.
3. Now you should see a new *"Custom"* option in the *Render Engine* selection dropdown menu. Select it and enable the *Render Preview* in the viewport. You should see the whole viewport with a flat green color.

**Comment by bxbrenden** [comment] 2020-12-11 03:01
Hey, nothing worse than a vague bug report 😉. On that note I forgot to mention the specifics of my embedded graphics on my laptop. Here is what `lspci` tells me:
```bash
$ lspci | grep VGA
00:02.0 VGA compatible controller: Intel Corporation UHD Graphics 620 (rev 07)
```
### Answers

1. Yes, this is the first and only Python traceback I get. If I change the viewport display to another setting like `Solid`, I get more Tracebacks, but they are more of the same.

2. F12 rendering is also solid black 100% of the time.

3. Yes, I can get the flat green render preview via the Simple Render Engine (see screenshot).

![Simple-Render-Engine](https://user-images.githubusercontent.com/26355516/101856236-bdd4e780-3b19-11eb-82ff-b73c0d4f12a9.png)

Let me know if I can provide anything else.

Thanks,
Brenden

**Comment by bxbrenden** [comment] 2021-01-18 04:34
Hi @pragma37, I was just curious if there are any updates on this. I'm excited to try Beer / Malt on Linux.

**Comment by pragma37** [comment] 2021-01-18 16:03
@bxbrenden I'm starting to work soon on an update to run Malt on a separate process. That should fix most OpenGL related issues.

I'll update this issue whenever I publish it. Thank you for your interest.

**Comment by pragma37** [comment] 2021-02-13 16:58
@bxbrenden  Could you try the new refactor branch? 

https://github.com/bnpr/Malt/releases/tag/v1-refactor

**Comment by bxbrenden** [comment] 2021-02-15 20:24
@pragma37 I tried with the newest Blender version `2.91.2` and the `Release v1-refactor`, and I got a Python traceback when clicking the check-box "Render: Blender Malt" to enable the Add-on in `Edit -> Preferences`. After the traceback, the Add-on still shows as disabled / unchecked. Screenshot and traceback below:
```bash
#( 02/15/21@12:15PM )( brenden@errmac ):~/Software/blender-2.91.2-linux64
   found bundled python: /home/brenden/Software/blender-2.91.2-linux64/2.91/python
Writing userprefs: '/home/brenden/Software/blender-2.91.2-linux64/2.91/config/userpref.blend' ok
addon_utils.disable: BlenderMalt not disabled
Modules Installed (BlenderMalt) from '/home/brenden/Software/BlenderMalt-Linux.zip' into '/home/brenden/Software/blender-2.91.2-linux64/2.91/scripts/addons'
Exception in module register(): /home/brenden/Software/blender-2.91.2-linux64/2.91/scripts/addons/BlenderMalt/__init__.py
Traceback (most recent call last):
  File "/home/brenden/Software/blender-2.91.2-linux64/2.91/scripts/modules/addon_utils.py", line 382, in enable
    mod.register()
  File "/home/brenden/Software/blender-2.91.2-linux64/2.91/scripts/addons/BlenderMalt/__init__.py", line 138, in register
    module.register()
  File "/home/brenden/Software/blender-2.91.2-linux64/2.91/scripts/addons/BlenderMalt/MaltPipeline.py", line 169, in register
    sys.executable = sys._base_executable
AttributeError: module 'sys' has no attribute '_base_executable'
```
![Malt-Addon-AttributeError](https://user-images.githubusercontent.com/26355516/107990078-7b4fe100-6f88-11eb-82b0-bdd7715c4a0e.png)

**Comment by pragma37** [comment] 2021-02-16 19:12
Oops! Sorry, that should be fixed now.

**Comment by bxbrenden** [comment] 2021-02-17 07:37
@pragma37 I downloaded the newest version of your Linux `Release v1-refactor`, and I made it further this time. I was able to enable the Add-on and change the Render Engine to Malt. But, it froze right when I did, and there was a Python traceback in the terminal. Based on the error, it appears the Add-on is trying to do some OS-level tweaks to renice the process, and it's getting `PermissionError` and `AccessDenied` exceptions.

Below is a copy of the whole console output, a set of steps to reproduce, and a screenshot of the frozen Blender screen.

## Console output
```bash
#( 02/16/21@11:21PM )( brenden@errmac ):~/Software
   addon_utils.disable: BlenderMalt not disabled
Modules Installed (BlenderMalt) from '/home/brenden/Software/BlenderMalt-Linux.zip' into '/home/brenden/Software/blender-2.91.2-linux64/2.91/scripts/addons'
Process Process-2:
Traceback (most recent call last):
  File "/home/brenden/Software/blender-2.91.2-linux64/2.91/scripts/addons/BlenderMalt/.MaltPath/Malt/.Dependencies/psutil/_pslinux.py", line 1576, in wrapper
    return fun(self, *args, **kwargs)
  File "/home/brenden/Software/blender-2.91.2-linux64/2.91/scripts/addons/BlenderMalt/.MaltPath/Malt/.Dependencies/psutil/_pslinux.py", line 1992, in nice_set
    return cext_posix.setpriority(self.pid, value)
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/brenden/Software/blender-2.91.2-linux64/2.91/python/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/brenden/Software/blender-2.91.2-linux64/2.91/python/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/brenden/Software/blender-2.91.2-linux64/2.91/scripts/addons/BlenderMalt/.MaltPath/Bridge/Server.py", line 153, in main
    psutil.Process(os.getpid()).nice(priority)
  File "/home/brenden/Software/blender-2.91.2-linux64/2.91/scripts/addons/BlenderMalt/.MaltPath/Malt/.Dependencies/psutil/__init__.py", line 724, in nice
    self._proc.nice_set(value)
  File "/home/brenden/Software/blender-2.91.2-linux64/2.91/scripts/addons/BlenderMalt/.MaltPath/Malt/.Dependencies/psutil/_pslinux.py", line 1578, in wrapper
    raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=6832)
```

## Steps to reproduce
1. Download the [v1-refactor](https://github.com/bnpr/Malt/releases/tag/v1-refactor) release.
2. Download Blender `2.91.2` from Blender.org.
3. Decompress the Blender 2.91.2 `tar.xz` file.
4. Change directories to the new Blender directory and then to the `2.91` directory within that.
5. Create a `config` directory there.
6. Start Blender.
7. Edit -> Preferences -> Add-ons.
8. Install...
9. Choose the `BlenderMalt.zip` file downloaded in step 1.
10. Click the check-box to enable the Add-on.
11. Go to `Scene` settings and choose `Malt` in the `Render Engine` drop-down.
12. The drop-down will permanently freeze with `Malt` highlighted.
13. You will see a traceback in your terminal matching the one I pasted in the above section

## Screenshot of frozen Blender screen
![MaltFrozen](https://user-images.githubusercontent.com/26355516/108170021-68373100-70ae-11eb-8236-93c4e51920ce.png)

**Comment by pragma37** [comment] 2021-02-19 19:22
Sorry for the issues.
The latest build works for me on Ubuntu and Manjaro.

**Comment by bxbrenden** [comment] 2021-02-19 22:51
@pragma37 it works now! Using the newest build of the `v1-refactor` release I was able to follow the YouTube tutorial fully! You can consider this issue closed. Thanks for all of your awesome work!

**Comment by pragma37** [comment] 2021-02-20 18:10
Great! Glad to see the refactor is paying off.
I'm closing this issue then.

**Closed by pragma37** 2021-02-20 18:10 UTC
