### ISSUE TITLE
Malt node preview shader compilation does not work

### ISSUE THREAD

**Issue by POPREQ** [bnpr/Malt#86] opened 2021-06-06 00:43 UTC
[Malt_issue_210606.zip](https://github.com/bnpr/Malt/files/6603441/Malt_issue_210606.zip)

https://www.patreon.com/posts/malt-nodes-51446027
I was using the node preview version of Malt, and sometimes the Shader would not compile.
Even if I reconnected the nodes, the new drawing state would not appear, but changing the values of the old nodes that were not connected would cause the drawing to change.

I can't find a specific condition for it.
I could not find a specific condition, but it happened when I created a frame with Ctrl+J, or when I created multiple gradients.

I've attached the log file and .blend data, but I'm new to GitHub communication and bug reporting, so please let me know if I'm doing something wrong.

**Comment by POPREQ** [comment] 2021-06-06 00:50
[node utils2.zip](https://github.com/bnpr/Malt/files/6603453/node.utils2.zip)

Sorry, there was something missing in the .blend file I just created.
I had added a few nodes to your distribution of node utils and loaded them in. I'm attaching that as well.
(The only additional node used is the float min function).

**Comment by pragma37** [comment] 2021-06-06 20:58
Hi! Good report.

The issue in the blend file you attached is caused by the re-route nodes. If you delete them it works.

This was an oversight on my side, right now Malt assumes all nodes are Malt Nodes.
I'll fix it as soon as possible.

**Comment by POPREQ** [comment] 2021-06-08 13:43
By eliminating the reroute node, the preview now works properly in my environment.
Glad I could contribute to the development!

**Comment by pragma37** [comment] 2021-06-21 14:57
The issue with the reroute node should be fixed in the latest version.

**Closed by pragma37** 2021-06-21 14:57 UTC
