### ISSUE TITLE
F12/ viewport rendering (not render preview) blank on Intel 620hd Graphics

### ISSUE THREAD

**Issue by OmniConsUme** [bnpr/Malt#23] opened 2020-12-09 21:53 UTC
Yeah I did check here a lot because f12 rendering issues seems to be almost common for different reasons,

Note: I did check blender 2.90 to confirm if it was just because 2.91 issues, but that version doesn't work either

Render preview works fine, however it seems the latest Beer version lags during shader compilation, when it originally just showed a yellow material after first clicking on it (jumping back to solid and back to render preview fixed it before).

Also before you ask, Cycles and Eevee work fine on my end.

**Comment by pragma37** [comment] 2020-12-10 14:31
Hi. I need more info to solve this issue:

https://github.com/BlenderNPR/BEER/tree/master/BlenderMalt#bug-reports

**Comment by OmniConsUme** [comment] 2020-12-10 17:52
Okay:

`Read prefs: C:\Users\bh630\AppData\Roaming\Blender Foundation\Blender\2.90\config\userpref.blend
found bundled python: C:\Users\bh630\Desktop\Creative\3D Modeling\blender\blender-2.90.0-windows64\2.90\python
Traceback (most recent call last):
  File "C:\Users\bh630\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlenderMalt\MaltPipeline.py", line 110, in depsgraph_update
    setup_all_ids()
  File "C:\Users\bh630\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlenderMalt\MaltPipeline.py", line 93, in setup_all_ids
    setup_parameters(bpy.data.scenes)
  File "C:\Users\bh630\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlenderMalt\MaltPipeline.py", line 71, in setup_parameters
    pipeline_parameters = get_pipeline().get_parameters()
  File "C:\Users\bh630\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlenderMalt\MaltPipeline.py", line 22, in get_pipeline
    bpy.context.scene.world.malt.update_pipeline(bpy.context)
  File "C:\Users\bh630\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlenderMalt\MaltPipeline.py", line 40, in update_pipeline
    __PIPELINE__ = _cls()
  File "C:\Users\bh630\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlenderMalt\MaltPath\Malt\Pipelines\NPR_Pipeline\NPR_Pipeline.py", line 50, in __init__
    super().__init__()
  File "C:\Users\bh630\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlenderMalt\MaltPath\Malt\Pipeline.py", line 89, in __init__
    self.quad = Mesh(positions, indices)
  File "C:\Users\bh630\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlenderMalt\MaltPath\Malt\Mesh.py", line 24, in __init__
    glGenBuffers(1, self.EBO)
  File "src/latebind.pyx", line 39, in OpenGL_accelerate.latebind.LateBind.__call__
  File "src/wrapper.pyx", line 318, in OpenGL_accelerate.wrapper.Wrapper.__call__
  File "src/wrapper.pyx", line 311, in OpenGL_accelerate.wrapper.Wrapper.__call__
  File "C:\Users\bh630\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlenderMalt\MaltDependencies\OpenGL\platform\baseplatform.py", line 415, in __call__
    return self( *args, **named )
  File "src/errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
OpenGL.error.GLError: GLError(
        err = 1280,
        description = b'invalid enumerant',
        baseOperation = glGenBuffers,
        pyArgs = (
                1,
                <Malt.GL.c_long_Array_1 object at 0x000001D2AB761348>,
        ),
        cArgs = (
                1,
                <Malt.GL.c_long_Array_1 object at 0x000001D2AB761348>,
        ),
        cArguments = (
                1,
                <Malt.GL.c_long_Array_1 object at 0x000001D2AB761348>,
        )
)
Unable to load numpy_formathandler accelerator from OpenGL_accelerate
Cycles OpenCL: driver crashed, continuing without OpenCL.
OpenCL error: CL_DEVICE_NOT_FOUND in device_opencl_get_num_platforms_safe(&num_platforms) (C:\b\buildbot-worker-windows\windows_290\blender.git\intern\cycles\device\device_opencl.cpp:144)
Traceback (most recent call last):
  File "C:\Users\bh630\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlenderMalt\MaltRenderEngine.py", line 270, in view_draw
    GL.glGetIntegerv(GL.GL_FRAMEBUFFER_BINDING, fbo)
  File "src/latebind.pyx", line 39, in OpenGL_accelerate.latebind.LateBind.__call__
  File "src/wrapper.pyx", line 318, in OpenGL_accelerate.wrapper.Wrapper.__call__
  File "src/wrapper.pyx", line 311, in OpenGL_accelerate.wrapper.Wrapper.__call__
  File "src/errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
OpenGL.error.GLError: GLError(
        err = 1280,
        description = b'invalid enumerant',
        baseOperation = glGetIntegerv,
        pyArgs = (
                GL_FRAMEBUFFER_BINDING,
                <Malt.GL.c_long_Array_1 object at 0x000001D2AB7CAE48>,
        ),
        cArgs = (
                GL_FRAMEBUFFER_BINDING,
                <Malt.GL.c_long_Array_1 object at 0x000001D2AB7CAE48>,
        ),
        cArguments = (
                GL_FRAMEBUFFER_BINDING,
                <Malt.GL.c_long_Array_1 object at 0x000001D2AB7CAE48>,
        )
)

location: <unknown location>:-1

location: <unknown location>:-1
Traceback (most recent call last):
  File "C:\Users\bh630\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlenderMalt\MaltRenderEngine.py", line 206, in render
    scene = self.get_scene(None, depsgraph, True)
  File "C:\Users\bh630\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlenderMalt\MaltRenderEngine.py", line 179, in get_scene
    add_object(obj, obj.matrix_world)
  File "C:\Users\bh630\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlenderMalt\MaltRenderEngine.py", line 110, in add_object
    malt_mesh = MaltMeshes.load_mesh(obj)
  File "C:\Users\bh630\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlenderMalt\MaltMeshes.py", line 84, in load_mesh
    positions = load_VBO(positions)
  File "C:\Users\bh630\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlenderMalt\MaltMeshes.py", line 78, in load_VBO
    glGenBuffers(1, VBO)
  File "src/latebind.pyx", line 39, in OpenGL_accelerate.latebind.LateBind.__call__
  File "src/wrapper.pyx", line 318, in OpenGL_accelerate.wrapper.Wrapper.__call__
  File "src/wrapper.pyx", line 311, in OpenGL_accelerate.wrapper.Wrapper.__call__
  File "src/errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
OpenGL.error.GLError: GLError(
        err = 1280,
        description = b'invalid enumerant',
        baseOperation = glGenBuffers,
        pyArgs = (
                1,
                <Malt.GL.c_long_Array_1 object at 0x000001D2AB7A4048>,
        ),
        cArgs = (
                1,
                <Malt.GL.c_long_Array_1 object at 0x000001D2AB7A4048>,
        ),
        cArguments = (
                1,
                <Malt.GL.c_long_Array_1 object at 0x000001D2AB7A4048>,
        )
)

location: <unknown location>:-1

location: <unknown location>:-1






[system-info.txt](https://github.com/BlenderNPR/BEER/files/5674715/system-info.txt)
`

**Comment by pragma37** [comment] 2020-12-10 23:24
That's strange.

In the Blender session from your log you enabled viewport rendering first and it worked. Is that right?

It's failing because there's not an OpenGL context active at render time, so any call to OpenGL fails. This is handled by Blender itself, so I don't have an inmediate way to fix it.

I've tried to reproduce this issue on my (older) integrated Intel GPU but it constantly runs out of memory.
However I managed to get F12 working with a dummy pipeline that only renders the background color, so it doesn't seem to be an issue that affects all Intel GPUs.

Maybe try to update your GPU drivers ?

**Comment by OmniConsUme** [comment] 2020-12-11 01:05
Yeah, that's a Huge problem! However, which is really weird earlier That I mentioned that both Cycles and Eevee, works fine, I will update gpu drivers to latest version available.

**Comment by pragma37** [comment] 2020-12-13 21:58
Lower performance is expected since I implemented some rendering features that affects performance even when not used.
Try lowering the Shadowmaps resolution and the Transparency Layers in the Scene settings.

The F12 issue will have to wait, since this kind of problems that only affects certain hardware are tipically very time consuming to solve. Sorry for that, but since I'm the only dev I have to prioritize at some point.

**Comment by douglaskastle** [comment] 2020-12-16 16:16
Observed this problem too on an Intel 530HD graphics card, which is on a 4 year old computer. Also see the performance lag when trying to change basic settings like color or line widths

**Comment by OmniConsUme** [comment] 2020-12-16 16:49
> 
> 
> Observed this problem too on an Intel 530HD graphics card, which is on a 4 year old computer. Also see the performance lag when trying to change basic settings like color or line widths

which problem is that, the f12 not rendering, or the slowdown, because the slowdown he said earlier on can be fixed by lowering setting, the f12 issue is the main problem I have?

**Comment by douglaskastle** [comment] 2020-12-16 20:30
@OmniConsUme

Yes the F12 problem is what I observed

**Comment by RangerXiang-github** [comment] 2021-01-10 02:51
Observed this problem too on GeForce RTX 2060, when pressed F12, shown blank in rendering window and Time:00:00.56
<img width="565" alt="shot" src="https://user-images.githubusercontent.com/16497406/104113151-baf42f00-5331-11eb-8e35-a8fd4edb531b.PNG">

**Comment by OmniConsUme** [comment] 2021-02-13 05:17
Update after Malt Refactor... It works, While I was eventually getting a new computer, with a non Intel GPU. It now works on my end... not sure If i should close this for the other people on this thread need to confirm if it works or not.

**Comment by pragma37** [comment] 2021-02-13 16:56
@OmniConsUme Thanks for reporting.

I think it's fair to assume this should be fixed now.

**Closed by pragma37** 2021-02-13 16:56 UTC
